export function usePngs() {
  return {
    SetaEsquerda: "../icons/png/SetaEsquerda.png",
    Tudo: "../icons/png/Tudo.png",
    Barraca: "../icons/png/Barraca.png",
    Bebidas: "../icons/png/Bebidas.png",
    Bolo: "../icons/png/Bolo.png",
    Cachorro: "../icons/png/Cachorro.png",
    Carro: "../icons/png/Carro.png",
    Coxinhas: "../icons/png/Coxinhas.png",
    Geladeira: "../icons/png/Geladeira.png",
    Hamburguer: "../icons/png/Hamburguer.png",
    HomemBarra: "../icons/png/HomemBarra.png",
    Joystick: "../icons/png/Joystick.png",
    Livros: "../icons/png/Livros.png",
    Mobilha: "../icons/png/Mobilha.png",
    Notebook: "../icons/png/Notebook.png",
    Parede: "../icons/png/Parede.png",
    Pizza: "../icons/png/Pizza.png",
    Roupas: "../icons/png/Roupas.png",
    Sorvete: "../icons/png/Sorvete.png",
    Tenis: "../icons/png/Tenis.png",
    Violao: "../icons/png/Violao.png",
    SetaDireita: "../icons/png/SetaDireita.png",
  };
}
